name: build-and-test

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4

      - uses: dylan-lang/install-dylan-tool@v2

      - name: Build dylan-brainfuck-tests
        run: | 
          dylan update
          dylan build brainfuck-test-suite

      - name: Run dylan-brainfuck-tests
        run: _build/bin/brainfuck-test-suite
